### ISSUE TITLE
Add a startup mode that enables using env variables instead of CLI arguments

### ISSUE THREAD

**Issue by nektro** [nektro/andesite#26]

**Comment by riptl** [comment]
I did this with cobra + viper [in od-database-crawler](https://github.com/terorie/od-database-crawler/blob/d3c199b738870d5934213e3152a8af43610ad484/config.go#L32), maybe it helps.

It supports config via `yaml`, `json`, flags and environment.

e.g. `--output.log` = `{"output": {"log": "value"}}` = `$OD_OUTPUT_LOG`

**Comment by nektro** [comment]
So, this issue was created in order to help enable #27, however they can be used separately. I could add a function that was similar to the following (I'll see if this is what viper does)
```go
func getProp(name string) {
    if args.Has(name) { return args.Get(name); }
    if env.Has(name) { return env.Get(name); }
    return default;
}
```

**Comment by riptl** [comment]
@nektro Viper is a key-value storage. If it doesn't find anything in-memory, it'll look in environment.
So it essentially does the same, I guess.
