### ISSUE TITLE
--admin parameter fails to set a previous visitor as admin without additional intervention

### ISSUE THREAD

**Issue by KNOXDEV** [nektro/andesite#32]
Just a very basic issue. Should be a quick fix. I don't have extensive knowledge of andesite internals yet so bare with me if I'm mistaken about anything.
# Expected Behavior
If a user with no permissions attempt to login, and I then boot andesite with the --admin parameter set to that existing user id, I should then be able to login as that user and have admin privileges.
# Problematic Behavior
The above user will still lack the ability to view the directory at all despite having admin permissions. This is inconsistent behavior to what happens when adding a user who has not attempted to login yet, as the added user can instantly view and manage the andesite instance. This can cause potential issues when configuring for the first time.
# How to Reproduce
Visit an andesite instance and attempt to login with an unregistered user. Once denied, reboot the server with the --admin parameter set to that user's ID. Attempting the login again will still deny access.
# Suggested Fixes
Assuming that the admin permission is being set correctly in both cases:
1) allow all admin users to view the directory regardless of other permissions OR
2) explicitly give existing users who are set to admin viewing permissions when the --admin parameter is processed

Feedback on the format is appreciated.

**Comment by nektro** [comment]
So you'd like for all admin users to automatically gain access to `/` as well?

**Comment by KNOXDEV** [comment]
That technically works. Admin users DO gain access to / when added, UNLESS you add them after they’ve already visited the site before. The inconsistent behavior is the real problem.

**Comment by nektro** [comment]
Okay, I will push a fix for this shortly.

Once updated with `go get -u` and restarting andesite with the `--admin` option should provide the new functionality.
