### ISSUE TITLE
Add support for Gitea OAuth

### ISSUE THREAD

**Issue by KNOXDEV** [nektro/andesite#33]
As long as this is a project for self-hosted open directories, we might as well add support for self-hosted github-like services like Gitea: https://docs.gitea.io/en-us/oauth2-provider/

Shouldn't require anything complex on top of what the Github OAuth already does other than the ability to configure the Gitea instance hostname in `config.json`, which is arguably what the Github configuration should already have since self-hosted Github Enterprise is a thing.

**Comment by KNOXDEV** [comment]
Just briefly glancing at the project structure, it seems like OAuth is provided by your external library, https://github.com/nektro/go.oauth2

There's nothing wrong with this, but the project doesn't seem to have support for configuring providers with a custom hostname, which means adding this kind of support isn't 100% drop in addable without a few structure changes. In other words, it might be involved.

**Comment by nektro** [comment]
Since GitTea is a self-hosted service it cannot be added to nektro/go.oauth2 as a pre-loaded identity provider, but I also just created #34 which should solve this issue and support more self-hosted services in the future.

**Comment by nektro** [comment]
A section will be needed to be added to `config.json` that allows users to load their own `Provider`s at outlined in https://github.com/nektro/go.oauth2/blob/master/provider.go

**Comment by KNOXDEV** [comment]
Alright, so long as there's a solution.
