### ISSUE TITLE
Consider using a language independant build system like make

### ISSUE THREAD

**Issue by KNOXDEV** [nektro/andesite#36]
Title says most of it. If we're going to create a more involved, dynamic frontend, we'll possibly need to overlap a new build system that can process these new systems in addition to go build, which we already use. In order to not directly affect the existing process, to create a single point of interaction for the developer and simplify the build process, i propose using the incredible widespread make system.
 # Example usage
```bash
# to build (will handle packr and the rest in one step)
make
# to build the front end
make frontend
# to run the result
make run
# to install as a service
make install
```
As you can see, this stands to drastically simplify the existing build process, it will integrate seamlessly with IDEs, and is very simple to maintain/extend to our future build process which may be more complex. 

Make is a guaranteed package on 90% of Linux systems, and Windows developers are already required to have GCC installed to compile this project, which in most Windows-based GCC distributions already come with make.

Let me know if making this change to the build system will cause any foreseeable issues.

**Comment by KNOXDEV** [comment]
Also, to be explicit, I will personally take care of this unless otherwise instructed. A PR will be submitted tomorrow.

**Comment by fieu** [comment]
@KNOXDEV It's been a little bit since "tomorrow" lmao

**Comment by nektro** [comment]
Unless @KNOXDEV submits this PR, I will be adding this soon myself.
