### ISSUE TITLE
Discord OAuth break with unusual port configurations

### ISSUE THREAD

**Issue by KNOXDEV** [nektro/andesite#38]
Running Andesite on a non-typical port, just as 8000 (the unconfigured default), will cause issues in the redirect url when attempting to log into Discord. 

As we can see, the redirect url is being sent to Discord correctly: 
![image](https://user-images.githubusercontent.com/5607614/58997615-41d64280-87b2-11e9-9f58-9a90ee9416c6.png)
...but Discord doesn't like port numbers in its redirect url:
![image](https://user-images.githubusercontent.com/5607614/58997638-587c9980-87b2-11e9-95f7-216115a77279.png)

Not sure what to do about this, since its mostly Discord's fault. Figured I'd better document the issue regardless of if we plan to fix it.

**Comment by nektro** [comment]
This is an behavior with Discord where they only whitelist `localhost:80` and `localhost:443` outright. So use of non-standard ports has to be added to your list of valid redirects on the Discord developers dashboard.

![image](https://user-images.githubusercontent.com/5464072/58998615-9b009f00-87cf-11e9-87c3-496fa9ae0a8f.png)

**Comment by KNOXDEV** [comment]
Good to know. Leave this issue intact and we should link to it in a future FAQ.
