### ISSUE TITLE
Display directory size.

### ISSUE THREAD

**Issue by catthehacker** [nektro/andesite#74]
.

**Comment by nektro** [comment]
Directory size requires search to be enabled for directory size to show up, but I've also noticed that the file count shows up blank, which should be there regardless.

**Comment by catthehacker** [comment]
![image](https://user-images.githubusercontent.com/31106839/82085241-3555ac00-96dc-11ea-922b-916a939bfbbd.png)
It's enabled.
<https://andesite.trademark.cat>

**Comment by nektro** [comment]
the proper usage is `--enable-search public` without the slash
