### ISSUE TITLE
Allow search to be separate for each root

### ISSUE THREAD

**Issue by catthehacker** [nektro/andesite#82]
e.g.: root called PolArt `domain.tld/PolArt/search` would show results only for that root

**Comment by nektro** [comment]
would this make it impossible to have a file named `search` in `PolArt` and any other roots?

**Comment by catthehacker** [comment]
Yes, but I assume the point of roots is that they are separated and no one can know about just from the application. Going to search I can find all my roots which kind of defeats the purpose of roots. One option would be to make search as GET `domain.tld/PolArt/?action=search`

**Comment by nektro** [comment]
It only shows the roots you can "see", that being public roots and any private ones you've been given view access to. This behavior could change or put behind a flag.

**Comment by catthehacker** [comment]
> would this make it impossible to have a file named `search` in `PolArt` and any other roots?

Doesn't it make impossible to have root called `search`?



> `domain.tld/PolArt/?action=search`

Better one, `domain.tld/search/root_name` that could be enabled by flag/config to scope search to specific roots and global search is unavailable/only for admin/s/discord group/etc.
