### ISSUE TITLE
Connection is reset when downloading big files

### ISSUE THREAD

**Issue by catthehacker** [nektro/andesite#86]
Happens since around andesite v53 maybe a bit earlier

**Comment by nektro** [comment]
What counts as a "big file" ?

Does this happen with the binary / docker container / both?

Does this happen on Web / CLI / both ?

**Comment by PanekJ** [comment]
I didn't tried browser, only wget. It happens on a binary and docker.

**Comment by catthehacker** [comment]
> What counts as a "big file" ?  

2GB - 1TB
> Does this happen with the binary / docker container / both?  

both 
> Does this happen on Web / CLI / both ?  

I tried wget, most likely it happens through web as well

**Comment by WatchCollector67** [comment]
The issue seems present on downloads with the web UI, rclone and wget. The issue still persists. I've found files that are 200MB failing if the connection is slow enough to make it download for more than a minute.

**Comment by nektro** [comment]
This is because of https://github.com/nektro/go.etc/blob/master/htp/htp.go#L114

This was added after the switch to https://github.com/gorilla/mux as the http router and using their Server config from the README.

https://github.com/gorilla/mux/blob/master/README.md#L203-L209

However, given that the request handlers are tested, the `WriteTimeout` is not necessary.

**Comment by nektro** [comment]
This is the culprit:
https://github.com/nektro/go.etc/commit/964147eb841143efc115e3c842101592d6958493

https://github.com/nektro/go.etc/blob/964147eb841143efc115e3c842101592d6958493/etc.go#L201-L207
vs
https://github.com/nektro/go.etc/blob/15bf861993f04caa3bc35c062936adc57ce4d128/etc.go#L194

Unfortunately, that would put the cause of this issue at `Feb 23` which I'm not sure if that's consistent with how long this issue has been present.

**Comment by nektro** [comment]
Tried a slow download over `wget` and the resets are at exactly `2,621,440` byte intervals.

![image](https://user-images.githubusercontent.com/5464072/93146445-b0879880-f6a3-11ea-8937-75bab66ee900.png)

**Comment by nektro** [comment]
Removing the timeout again seems promising

![image](https://user-images.githubusercontent.com/5464072/93147266-98187d80-f6a5-11ea-850c-32bbd5ac2b1a.png)
